// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vmaiqmycljvglkptjbuz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtYWlxbXljbGp2Z2xrcHRqYnV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MjA5OTUsImV4cCI6MjA2Nzk5Njk5NX0.UjFFn5XPgbsieEAq4mGbjvhTSttLN3nfmHUQM9rKItY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});